"""recurring rules, etc.

Revision ID: 0a5e0cfc02f5
Revises: c30fad85c2d9
Create Date: 2025-12-26 16:21:59.410432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a5e0cfc02f5'
down_revision: Union[str, Sequence[str], None] = 'c30fad85c2d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_intake', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_id', sa.String(), nullable=True))
        batch_op.alter_column('custom_recurring_rules',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_column('ein')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_id', sa.String(), nullable=True))
        batch_op.drop_column('ein')

    with op.batch_alter_table('recurring_template_tasks', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('schedule_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'client_frequency'"))
        batch_op.alter_column('default_assigned_role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('default_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'open'"))
        batch_op.create_index(batch_op.f('ix_recurring_template_tasks_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_template_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_template_tasks_id'))
        batch_op.alter_column('default_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'open'"))
        batch_op.alter_column('default_assigned_role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('schedule_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'client_frequency'"))
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ein', sa.TEXT(), nullable=True))
        batch_op.drop_column('tax_id')

    with op.batch_alter_table('client_intake', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ein', sa.TEXT(), nullable=True))
        batch_op.alter_column('custom_recurring_rules',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('tax_id')

    # ### end Alembic commands ###
