"""monthly tiers, etc.

Revision ID: 87d8bfdee3b4
Revises: c91d0e1a2b3c
Create Date: 2026-01-02 15:07:27.511467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d8bfdee3b4'
down_revision: Union[str, Sequence[str], None] = 'c91d0e1a2b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_intake', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qbo_num_classes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qbo_num_locations', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('non_business_deposits_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('personal_expenses_in_business_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('business_expenses_in_personal_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('monthly_close_tier', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_manager_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_manager_id'), ['manager_id'], unique=False)

    with op.batch_alter_table('client_intake', schema=None) as batch_op:
        batch_op.drop_column('monthly_close_tier')
        batch_op.drop_column('business_expenses_in_personal_details')
        batch_op.drop_column('personal_expenses_in_business_details')
        batch_op.drop_column('non_business_deposits_details')
        batch_op.drop_column('qbo_num_locations')
        batch_op.drop_column('qbo_num_classes')

    # ### end Alembic commands ###
