"""Permissions / Client Access

Revision ID: 98b50b3a6b25
Revises: 670360214412
Create Date: 2025-12-18 14:21:44.603991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b50b3a6b25'
down_revision: Union[str, Sequence[str], None] = '670360214412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_user_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('can_upload_docs', sa.Boolean(), nullable=False),
    sa.Column('can_view_tasks', sa.Boolean(), nullable=False),
    sa.Column('can_message', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'user_id', name='uq_client_user')
    )
    with op.batch_alter_table('client_user_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_user_access_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_user_access_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_user_access_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_user_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_user_access_user_id'))
        batch_op.drop_index(batch_op.f('ix_client_user_access_id'))
        batch_op.drop_index(batch_op.f('ix_client_user_access_client_id'))

    op.drop_table('client_user_access')
    # ### end Alembic commands ###
