"""initial schema

Revision ID: edf72140cf58
Revises: 
Create Date: 2025-12-08 12:16:02.797140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf72140cf58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_client', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_id'), ['id'], unique=False)

    op.create_table('onboarding_template_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('default_due_offset_days', sa.Integer(), nullable=True),
    sa.Column('default_assigned_role', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onboarding_template_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_template_tasks_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('dba_name', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('billing_frequency', sa.String(), nullable=True),
    sa.Column('bookkeeping_frequency', sa.String(), nullable=True),
    sa.Column('primary_contact', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('cpa', sa.String(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('bookkeeper_id', sa.Integer(), nullable=True),
    sa.Column('primary_contact_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bookkeeper_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['primary_contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_primary_contact_id'), ['primary_contact_id'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('last4', sa.String(length=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_id'), ['id'], unique=False)

    op.create_table('client_intake',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('dba_name', sa.String(), nullable=True),
    sa.Column('business_address', sa.String(), nullable=True),
    sa.Column('tax_structure', sa.String(), nullable=True),
    sa.Column('owners', sa.Text(), nullable=True),
    sa.Column('primary_contact_name', sa.String(), nullable=True),
    sa.Column('primary_contact_email', sa.String(), nullable=True),
    sa.Column('primary_contact_phone', sa.String(), nullable=True),
    sa.Column('primary_contact_id', sa.Integer(), nullable=True),
    sa.Column('cpa_contact_id', sa.Integer(), nullable=True),
    sa.Column('bookkeeping_start_date', sa.Date(), nullable=True),
    sa.Column('qbo_exists', sa.Boolean(), nullable=True),
    sa.Column('allow_login_access', sa.Boolean(), nullable=True),
    sa.Column('qbo_status', sa.String(), nullable=True),
    sa.Column('qbo_num_users', sa.Integer(), nullable=True),
    sa.Column('qbo_needs_class_tracking', sa.Boolean(), nullable=False),
    sa.Column('qbo_needs_location_tracking', sa.Boolean(), nullable=False),
    sa.Column('qbo_recommended_subscription', sa.String(), nullable=True),
    sa.Column('num_checking', sa.Integer(), nullable=True),
    sa.Column('checking_banks', sa.Text(), nullable=True),
    sa.Column('num_savings', sa.Integer(), nullable=True),
    sa.Column('savings_banks', sa.Text(), nullable=True),
    sa.Column('num_credit_cards', sa.Integer(), nullable=True),
    sa.Column('credit_card_banks', sa.Text(), nullable=True),
    sa.Column('loans', sa.Text(), nullable=True),
    sa.Column('vehicles', sa.Text(), nullable=True),
    sa.Column('assets', sa.Text(), nullable=True),
    sa.Column('payment_methods', sa.Text(), nullable=True),
    sa.Column('non_business_deposits', sa.Boolean(), nullable=True),
    sa.Column('personal_expenses_in_business', sa.Boolean(), nullable=True),
    sa.Column('business_expenses_in_personal', sa.Boolean(), nullable=True),
    sa.Column('report_frequency', sa.String(), nullable=True),
    sa.Column('income_tracking', sa.Text(), nullable=True),
    sa.Column('payroll_provider', sa.String(), nullable=True),
    sa.Column('payroll_needs_setup', sa.Boolean(), nullable=False),
    sa.Column('payroll_process_regular', sa.Boolean(), nullable=False),
    sa.Column('payroll_corrections_adjustments', sa.Boolean(), nullable=False),
    sa.Column('payroll_quarterly_filings', sa.Boolean(), nullable=False),
    sa.Column('payroll_state_local_payments', sa.Boolean(), nullable=False),
    sa.Column('payroll_calculate_hours_commission', sa.Boolean(), nullable=False),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['cpa_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['primary_contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_intake', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_intake_cpa_contact_id'), ['cpa_contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_intake_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_intake_legal_name'), ['legal_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_intake_primary_contact_id'), ['primary_contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_intake_status'), ['status'], unique=False)

    op.create_table('client_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_notes_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_notes_id'), ['id'], unique=False)

    op.create_table('client_purge_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_purge_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_purge_requests_id'), ['id'], unique=False)

    op.create_table('recurring_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('schedule_type', sa.String(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('week_of_month', sa.Integer(), nullable=True),
    sa.Column('next_run', sa.Date(), nullable=False),
    sa.Column('default_status', sa.String(), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_tasks_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_tasks_id'), ['id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('stored_filename', sa.String(), nullable=False),
    sa.Column('stored_path', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)

    op.create_table('intake_owners',
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['intake_id'], ['client_intake.id'], ),
    sa.PrimaryKeyConstraint('intake_id', 'contact_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('recurring_task_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('onboarding_phase', sa.String(), nullable=True),
    sa.Column('template_task_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recurring_task_id'], ['recurring_tasks.id'], ),
    sa.ForeignKeyConstraint(['template_task_id'], ['onboarding_template_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_recurring_task_id'), ['recurring_task_id'], unique=False)

    op.create_table('task_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_notes_task_id'), ['task_id'], unique=False)

    op.create_table('task_subtasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_subtasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_subtasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_subtasks_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_subtasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_subtasks_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_subtasks_id'))

    op.drop_table('task_subtasks')
    with op.batch_alter_table('task_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_notes_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_notes_id'))

    op.drop_table('task_notes')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_recurring_task_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_id'))

    op.drop_table('tasks')
    op.drop_table('intake_owners')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_id'))
        batch_op.drop_index(batch_op.f('ix_documents_client_id'))
        batch_op.drop_index(batch_op.f('ix_documents_account_id'))

    op.drop_table('documents')
    with op.batch_alter_table('recurring_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_tasks_client_id'))

    op.drop_table('recurring_tasks')
    with op.batch_alter_table('client_purge_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_purge_requests_id'))

    op.drop_table('client_purge_requests')
    with op.batch_alter_table('client_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_notes_id'))
        batch_op.drop_index(batch_op.f('ix_client_notes_client_id'))

    op.drop_table('client_notes')
    with op.batch_alter_table('client_intake', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_intake_status'))
        batch_op.drop_index(batch_op.f('ix_client_intake_primary_contact_id'))
        batch_op.drop_index(batch_op.f('ix_client_intake_legal_name'))
        batch_op.drop_index(batch_op.f('ix_client_intake_id'))
        batch_op.drop_index(batch_op.f('ix_client_intake_cpa_contact_id'))

    op.drop_table('client_intake')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_client_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_primary_contact_id'))
        batch_op.drop_index(batch_op.f('ix_clients_id'))

    op.drop_table('clients')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('onboarding_template_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onboarding_template_tasks_id'))

    op.drop_table('onboarding_template_tasks')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_id'))

    op.drop_table('contacts')
    # ### end Alembic commands ###
